const products = [
  {
    id: 1,
    name: "Rose Glow Serum",
    price: 29.99,
    image: "/products/rose-glow-serum.jpg",
    category: "Skincare",
    icon: "/icons/rose-glow-serum.svg",
    emoji: "🌹",
  },
  {
    id: 2,
    name: "Velvet Matte Lipstick",
    price: 19.99,
    image: "/products/velvet-matte-lipstick.jpg",
    category: "Makeup",
    icon: "/icons/velvet-matte-lipstick.svg",
    emoji: "💄",
  },
  {
    id: 3,
    name: "Hydra Boost Cream",
    price: 34.99,
    image: "/products/hydra-boost-cream.jpg",
    category: "Skincare",
    icon: "/icons/hydra-boost-cream.svg",
    emoji: "🧴",
  },
  {
    id: 4,
    name: "Silk Touch Foundation",
    price: 39.99,
    image: "/products/silk-touch-foundation.jpg",
    category: "Makeup",
    icon: "/icons/silk-touch-foundation.svg",
    emoji: "🧴",
  },
  {
    id: 5,
    name: "Lash Lift Mascara",
    price: 24.99,
    image: "/products/lash-lift-mascara.jpg",
    category: "Makeup",
    icon: "/icons/lash-lift-mascara.svg",
    emoji: "👁️",
  },
  {
    id: 6,
    name: "Peach Blush Palette",
    price: 27.99,
    image: "/products/peach-blush-palette.jpg",
    category: "Makeup",
    icon: "/icons/peach-blush-palette.svg",
    emoji: "🎨",
  },
  {
    id: 7,
    name: "Amber Woods Perfume",
    price: 49.99,
    image: "/products/amber-woods-perfume.jpg",
    category: "Fragrance",
    icon: "/icons/amber-woods-perfume.svg",
    emoji: "🧴",
  },
  {
    id: 8,
    name: "Citrus Bloom Eau de Toilette",
    price: 44.99,
    image: "/products/citrus-bloom-eau-de-toilette-perfume.jpg",
    category: "Fragrance",
    icon: "/icons/citrus-bloom-eau-de-toilette.svg",
    emoji: "🍊",
  },
  {
    id: 9,
    name: "Green Tea Face Wash",
    price: 15.99,
    image: "/products/green-tea-face-wash.jpg",
    category: "Skincare",
    icon: "/icons/green-tea-face-wash.svg",
    emoji: "🍃",
  },
  {
    id: 10,
    name: "Vitamin C Night Cream",
    price: 32.99,
    image: "/products/vitamin-c-night-cream.jpg",
    category: "Skincare",
    icon: "/icons/vitamin-c-night-cream.svg",
    emoji: "🍊",
  },
  {
    id: 11,
    name: "Charcoal Detox Mask",
    price: 22.99,
    image: "/products/charcoal-detox-mask.jpg",
    category: "Skincare",
    icon: "/icons/charcoal-detox-mask.svg",
    emoji: "🪨",
  },
  {
    id: 12,
    name: "Berry Tint Lip Balm",
    price: 9.99,
    image: "/products/berry-tint-lip-balm.jpg",
    category: "Makeup",
    icon: "/icons/berry-tint-lip-balm.svg",
    emoji: "🍓",
  },
  {
    id: 13,
    name: "Golden Glow Highlighter",
    price: 21.99,
    image: "/products/golden-glow-highlighter.jpg",
    category: "Makeup",
    icon: "/icons/golden-glow-highlighter.svg",
    emoji: "✨",
  },
  {
    id: 14,
    name: "Ocean Breeze Body Mist",
    price: 18.99,
    image: "/products/ocean-breeze-body-mist.jpg",
    category: "Fragrance",
    icon: "/icons/ocean-breeze-body-mist.svg",
    emoji: "🌊",
  },
  {
    id: 15,
    name: "Jasmine Dream Perfume",
    price: 54.99,
    image: "/products/jasmine-dream-perfume.jpg",
    category: "Fragrance",
    icon: "/icons/jasmine-dream-perfume.svg",
    emoji: "🌼",
  },
  {
    id: 16,
    name: "Aloe Vera Gel",
    price: 12.99,
    image: "/products/aloe-vera-gel.jpg",
    category: "Skincare",
    icon: "/icons/aloe-vera-gel.svg",
    emoji: "🌱",
  },
  {
    id: 17,
    name: "Matte Perfection Compact",
    price: 25.99,
    image: "/products/matte-perfection-compactt.jpg",
    category: "Makeup",
    icon: "/icons/matte-perfection-compact.svg",
    emoji: "🪞",
  },
  {
    id: 18,
    name: "Rose Petal Toner",
    price: 17.99,
    image: "/products/rose-petal-toner.jpg",
    category: "Skincare",
    icon: "/icons/rose-petal-toner.svg",
    emoji: "🥀",
  },
  {
    id: 19,
    name: "Cocoa Butter Hand Cream",
    price: 14.99,
    image: "/products/cocoa-butter-hand-cream.jpg",
    category: "Skincare",
    icon: "/icons/cocoa-butter-hand-cream.svg",
    emoji: "🧴",
  },
  {
    id: 20,
    name: "Vanilla Spice Eau de Parfum",
    price: 59.99,
    image: "/products/vanilla-spice-eau-de-parfum.jpg",
    category: "Fragrance",
    icon: "/icons/vanilla-spice-eau-de-parfum.svg",
    emoji: "🍦",
  },
];

export default products; 